# Generated by Django 5.1.3 on 2024-12-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipinfo',
            old_name='phone_number',
            new_name='phone_num',
        ),
        migrations.RenameField(
            model_name='shipinfo',
            old_name='city',
            new_name='town',
        ),
        migrations.RenameField(
            model_name='shipinfo',
            old_name='postal_code',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='shipinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shipinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shipinfo',
            name='state',
        ),
        migrations.AddField(
            model_name='shipinfo',
            name='com',
            field=models.TextField(blank=True, null=True),
        ),
    ]
