# Generated by Django 5.1.3 on 2024-12-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_total_price'),
        ('shippinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shippinfo.shipinfo'),
        ),
    ]
